# path for item data
item_path: data/item.csv
# path for user data
user_path: data/user.csv
# path for relationship data
relationship_path: data/relationship.csv
# path for save interaction records
interaction_path: data/interaction.csv
# directory name for faiss index
index_name: data/faiss_index
# recommender system model
model: Random
# number of epochs
epoch: 1
# number of agents, which cannot exceed the number of user in user.csv
num_agents: 1
# number of items to be recommended in one page
page_size: 5
# temperature for LLM
temperature: 0.8
# maximum number of tokens for LLM
max_token: 1500
# execution mode, serial or parallel
execution_mode: serial
# list of api keys for LLM API
api_keys:
  - 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

