# path for item data
item_path: data/item.csv
# path for user data
user_path: data/user.csv
# path for relationship data
relationship_path: data/relationship.csv
# path for save interaction records
interaction_path: data/interaction.csv
# directory name for faiss index
index_name: data/faiss_index
# simulator directory name for saving and restoring
simulator_dir: data/simulator
# simulator restoring name
simulator_restore_file_name: 
# recommender system model
model: Random
# number of epochs
epoch: 4
# number of agents, which cannot exceed the number of user in user.csv
num_agents: 1
# number of items to be recommended in one page
page_size: 5
# temperature for LLM
temperature: 0.8
# maximum number of tokens for LLM
max_token: 1500
# execution mode, serial or parallel
execution_mode: serial
# list of api keys for LLM API
api_keys:
  - jpgSSLwTE1kUhJSgrNBaT3BlbkFJAz2jKODFtQo57REvlI8M
  - Txjvy0mTppqDn7NZ7SkCT3BlbkFJhdZtrvOT3UnCKeKmeZMe
  - wr3riCWf40AIaIJ8XV0mT3BlbkFJ8TGuioMZmGfpvHA4T3Ri


